DROP TABLE IF EXISTS Countries;

CREATE TABLE Countries(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_rus varchar(50) NOT NULL UNIQUE,
    name_eng varchar(50) NOT NULL UNIQUE,
    description     VARCHAR(1000),
    money int CHECK (money > 0)
);

INSERT INTO Countries(name_rus, name_eng, description, money) VALUES ("Магвол", "Magevall" , "", 1000);

DROP TABLE IF EXISTS Incoming;

CREATE TABLE Incoming(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    income int CHECK (income > 0)
);

INSERT INTO Incoming(income) VALUES (100);

DROP TABLE IF EXISTS Costs;

CREATE TABLE Costs(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost int CHECK (cost > 0)
);

INSERT INTO Costs(cost) VALUES (50);
